name: Restock Watcher

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 min UTC
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code _with_ write perms
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # so we can push commits

      # 2. Python setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install deps
        run: pip install -r requirements.txt

      # 4. Run your watcher (updates status.json)
      - name: Run restock script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python script.py

      # 5. Commit any changes to status.json
      - name: Commit updated status.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: chore: update status.json
          file_pattern: status.json
          branch: main
          # GITHUB_TOKEN is provided automatically, no need to set
