name: Restock Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore status.json cache
        id: cache
        uses: actions/cache@v3
        with:
          path: status.json
          key: matcha-snooper-state

      - name: Show *restored* status.json
        run: |
          echo "--- RESTORED status.json (cache-hit=${{ steps.cache.outputs.cache-hit }}) ---"
          if [ -f status.json ]; then cat status.json; else echo "(none)"; fi
          echo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run restock script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python script.py

      - name: Show *new* status.json
        run: |
          echo "--- NEW status.json ---"
          cat status.json
          echo

      - name: Save status.json to cache
        uses: actions/cache@v3
        with:
          path: status.json
          key: matcha-snooper-state

      - name: Upload status.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: status-json
          path: status.json
