name: Restock Watcher

# Grant write access so the auto-commit can push back to main
permissions:
  contents: write

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true # so the checkout action uses the token for pushes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run restock script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python script.py

      - name: Commit updated status.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update status.json"
          file_pattern: "status.json"
          branch: "main"
