name: Restock Watcher

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout with creds & full history so we can push
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. See what branch & remotes we have
      - name: Debug Git
        run: |
          echo "=== Git config ==="
          git config --list
          echo
          echo "=== Git status ==="
          git status
          echo
          echo "=== Branch & remote ==="
          git branch
          git remote -v

      # 3. Run your script
      - name: Run restock script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python script.py

      # 4. Show any diffs
      - name: Show diff
        run: |
          echo "=== After script, status.json diff ==="
          git status
          git diff

      # 5. Try to commit & push manually
      - name: Manual commit & push
        run: |
          git add status.json
          if git diff --cached; then
            git commit -m "ci: update status.json"
            git push origin main
          else
            echo "⏭️ No changes to commit"
          fi
